WITH ORA_read_EWM_EV_TXN_V AS (
    SELECT
        SRC_DL,
        EV_ID,
        MSTR_SRC_STM_CD,
        MSTR_SRC_STM_KEY,
        VLD_FROM_TMS,
        VLD_TO_TMS,
        PRIM_AR_ID,
        TXN_BOOK_DT,
        TXN_CCY_AMT,
        TXN_CCY_CL_CD,
        TXN_RSN_TP_CL_CD,
        LDGR_CCY_AMT,
        LDGR_CCY_CL_CD
    FROM
        #XG_PS_RDB_DM_MPSCR_DATABASE.$XG_RDB_DM_SCHEMA_MPSCR#.EWM_EV_TXN_V
    WHERE
        SRC_DL='#XG_PM_SRC_DL#'
        AND TXN_RSN_TP_CL_CD IN ('FEE_CMSN_PYMT', 'INT_PYMT', 'PNP_PYMT', 'PST_RSL_PYMT', 'TCNQL_PYMT', 'FNC_SVC_PYMT', 'ADL_WRKOUT_COST', 'ADMIN_RCVR_COST', 'EXT_COST', 'FEE_CMSN_CHRG', 'INT_CHRG', 'LGL_COST', 'LQD_COST', 'PST_RSL_COST', 'TCNQL_ADVNC_PYMT', 'PNP_ADVNC', 'FNC_SVC_CHRG', 'WRT_OFF', 'FNC_CLM', 'AGRM_NET_SALE')
        AND VLD_FROM_TMS <= TO_DATE('#XG_PM_SELECTION_DATE##XG_PM_BUSINESS_TMS#', 'YYYYMMDDHH24MISS')
        AND TO_DATE('#XG_PM_SELECTION_DATE##XG_PM_BUSINESS_TMS#', 'YYYYMMDDHH24MISS') < VLD_TO_TMS
),
RDU_MDM_FNL_AR_SRC AS (
    SELECT
        SRC_DL,
        EV_ID,
        MSTR_SRC_STM_CD,
        MSTR_SRC_STM_KEY,
        VLD_FROM_TMS,
        VLD_TO_TMS,
        PRIM_AR_ID,
        ROW_NUMBER() OVER (PARTITION BY SRC_DL, PRIM_AR_ID, FCY_RK, MSTR_SRC_STM_KEY ORDER BY SRC_DL) AS row_num
    FROM
        ORA_read_EWM_EV_TXN_V
)
SELECT
    SRC_DL,
    EV_ID,
    MSTR_SRC_STM_CD,
    MSTR_SRC_STM_KEY,
    VLD_FROM_TMS,
    VLD_TO_TMS,
    PRIM_AR_ID
FROM
    RDU_MDM_FNL_AR_SRC
WHERE
    row_num = 1;