WITH JNO_FCY_AR_LWST_HGHST AS (
    SELECT 
        t1.*, 
        t2.*
    FROM V438S1P1 t1
    LEFT OUTER JOIN V438S1P2 t2
    ON t1.SRC_DL = t2.SRC_DL AND t1.AR_ID = t2.AR_ID
),
RDU_Highest_Facility AS (
    SELECT *
    FROM V438S0P1
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SRC_DL, AR_ID ORDER BY SRC_DL, AR_ID) = 1
),
XFM_HIGHEST_FACILITY AS (
    SELECT 
        mov_AR_X_R_HIGHEST.HIGHEST_FCY_ID AS AR_ID,
        'Y' AS HIGHEST_FCY_IN_HRY
    FROM mov_AR_X_R_HIGHEST
)
SELECT 
    DATA_DT = TO_DATE('#XG_PM_SELECTION_DATE#','YYYYMMDD') AND SRC_DL = '#XG_PM_SRC_DL#' AS DATA_DT,
    Derived(renamed) OBJ_AR_ID AS FCY_ID,
    Derived(renamed) MSTR_SRC_STM_CD AS SRC_STM_ID
FROM 
    EWM_MDM_STAGE_FCY_AR_IP_JDCL,
    EWM_AR_X_AR_R